version: "2.2"

services:
  bot:
    container_name: sms_bot
    image: akafer/sms_bot
    restart: on-failure
    command: >
      bash -c ". venv/bin/activate
      && python3 my_store/sms_bot.py"
    volumes:
      - ./reports:/tmp
    env_file:
      - .env
